global:
  scrape_interval:      5s
  evaluation_interval:  5s

scrape_configs:
  - job_name: 'fuzzing_metrics'
    static_configs:
      - targets: ['statsd_exporter:9102']
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
